In [195]:
from eventio import IACTFile

In [196]:
f = IACTFile("/Users/dennisvanelten/Desktop/iceact/1_gamma_1.dat")

In [197]:
event = f[0]
event.header.total_energy #gibt die total_energy des Schauers in der .dat-Datei an (hier ca. 7 TeV)
event.photon_bunches[0].shape #gibt das Format an (hier etwa 4,2 Mio produzierte Photonen)

(4234814,)

In [198]:
photons = event.photon_bunches[0]

In [199]:
import numpy as np

In [200]:
r = np.sqrt(photons['x']**2 + photons['y']**2)
mask = r < 25.35
selected_photons = photons[mask]
#len(selected_photons)

In [201]:
import random

In [202]:
np.random.shuffle(selected_photons)
#selected_photons #gibt Photonen an, die innerhalb des Kreises (Detektor) liegen (hier: 38), aber random reihenfolge

In [203]:
import pandas as pd

In [204]:
response = pd.read_csv("/Users/dennisvanelten/instrument-response/famous-parameterization-simulation.csv", index_col = 0)

In [205]:
from scipy.spatial import KDTree

In [206]:
tree = KDTree(response[['u', 'v']].values)

In [207]:
#response.columns.values    #gibt alle Zeilenname von response wieder: u,v wurden addiert 

In [208]:
distances, indices = tree.query(np.column_stack([selected_photons['cx'], selected_photons['cy']]))

In [209]:
array = distances, indices
array

(array([ 0.00200096,  0.00262121,  0.00029361,  0.00044485,  0.00134578,
         0.00152909,  0.00226921,  0.00230328,  0.0018415 ,  0.00237993,
         0.00122817,  0.00113698,  0.0020065 ,  0.002217  ,  0.0024937 ,
         0.0013365 ,  0.00222609,  0.00161201,  0.00086056,  0.00186337,
         0.00196179,  0.00210569,  0.00067515,  0.0008076 ,  0.00227258,
         0.00166822,  0.00091577,  0.00108397,  0.00196618,  0.0018021 ,
         0.00232896,  0.00248224,  0.00194275,  0.00112329,  0.0014336 ,
         0.0019179 ,  0.00116499,  0.00245138]),
 array([ 20,  36, 344,  54,  76,   3, 539,  20,   9,   2,  77,  20,  77,
          2, 350,  54,   3,  10,  20,  20,   9,  35,   2,  20,   9,  10,
         10, 135,  21,  20,  21, 898,   9,  77,  20,   9,  11, 299]))

In [210]:
indices

array([ 20,  36, 344,  54,  76,   3, 539,  20,   9,   2,  77,  20,  77,
         2, 350,  54,   3,  10,  20,  20,   9,  35,   2,  20,   9,  10,
        10, 135,  21,  20,  21, 898,   9,  77,  20,   9,  11, 299])

In [211]:
#array[1][0]   #array[0] = distances   array[1] = indices
              #want special indice

In [212]:
response.head(len(response))

phi  t_sipm  t_sipm_0  t_sipm_1  t_sipm_10  t_sipm_11  t_sipm_12  \
0     0.785398  0.0787    0.0633    0.0042     0.0000     0.0000     0.0000   
1     2.356194  0.0775    0.0639    0.0000     0.0000     0.0000     0.0000   
2     3.926991  0.0773    0.0634    0.0000     0.0001     0.0000     0.0000   
3     5.497787  0.0746    0.0608    0.0050     0.0001     0.0000     0.0000   
4     0.392699  0.0814    0.0550    0.0144     0.0000     0.0000     0.0000   
5     1.178097  0.0813    0.0577    0.0012     0.0000     0.0000     0.0000   
6     1.963495  0.0882    0.0605    0.0000     0.0001     0.0000     0.0001   
7     2.748894  0.0793    0.0524    0.0000     0.0000     0.0000     0.0000   
8     3.534292  0.0815    0.0564    0.0001     0.0000     0.0000     0.0001   
9     4.319690  0.0844    0.0547    0.0000     0.0000     0.0000     0.0000   
10    5.105088  0.0910    0.0621    0.0022     0.0000     0.0000     0.0000   
11    5.890486  0.0808    0.0558    0.0118     0.0000     0.0000     0.0000   
12    0.261799  0.0818    0.0455    0.0203     0.0000     0.0000     0.0000   
13    0.785398  0.0812    0.0461    0.0126     0.0000     0.0000     0.0000   
14    1.308997  0.0865    0.0478    0.0001     0.0000     0.0000     0.0000   
15    1.832596  0.0847    0.0513    0.0000     0.0000     0.0000     0.0000   
16    2.356194  0.0839    0.0492    0.0000     0.0000     0.0000     0.0000   
17    2.879793  0.0777    0.0447    0.0000     0.0000     0.0000     0.0000   
18    3.403392  0.0807    0.0467    0.0000     0.0000     0.0000     0.0000   
19    3.926991  0.0820    0.0467    0.0001     0.0000     0.0000     0.0000   
20    4.450590  0.0843    0.0496    0.0000     0.0000     0.0000     0.0000   
21    4.974188  0.0805    0.0436    0.0000     0.0000     0.0000     0.0002   
22    5.497787  0.0831    0.0461    0.0138     0.0000     0.0000     0.0000   
23    6.021386  0.0841    0.0471    0.0227     0.0000     0.0000     0.0000   
24    0.196350  0.0855    0.0376    0.0301     0.0000     0.0001     0.0000   
25    0.589049  0.0879    0.0405    0.0217     0.0000     0.0000     0.0000   
26    0.981748  0.0854    0.0412    0.0106     0.0000     0.0000     0.0001   
27    1.374447  0.0884    0.0421    0.0000     0.0000     0.0000     0.0000   
28    1.767146  0.0848    0.0399    0.0000     0.0000     0.0000     0.0000   
29    2.159845  0.0890    0.0421    0.0000     0.0000     0.0000     0.0000   
...        ...     ...       ...       ...        ...        ...        ...   
5910  5.425065  0.0001    0.0000    0.0000     0.0000     0.0000     0.0000   
5911  5.454154  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5912  5.483243  0.0001    0.0000    0.0000     0.0000     0.0000     0.0000   
5913  5.512332  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5914  5.541420  0.0001    0.0000    0.0000     0.0000     0.0000     0.0000   
5915  5.570509  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5916  5.599598  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5917  5.628687  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5918  5.657776  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5919  5.686864  0.0001    0.0000    0.0000     0.0000     0.0000     0.0000   
5920  5.715953  0.0001    0.0000    0.0000     0.0000     0.0000     0.0000   
5921  5.745042  0.0002    0.0000    0.0000     0.0000     0.0000     0.0000   
5922  5.774131  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5923  5.803220  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5924  5.832309  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5925  5.861397  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5926  5.890486  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5927  5.919575  0.0000    0.0000    0.0000     0.0000     0.0000     0.0000   
5928  5.948664  0.0001    0.0000    0.0000     0.0000     0.0

In [213]:
#response.iloc[[5930]] #beispielhaft die komplette [...] Reihe ausgeben

In [214]:
response.index #gibt Namen aller rows aus

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            5930, 5931, 5932, 5933, 5934, 5935, 5936, 5937, 5938, 5939],
           dtype='int64', length=5940)

In [215]:
response_cols = response.iloc[:,2:63]    
response_cols     #hier wird nun die gesamte Tabelle ausgegeben, jedoch in den Zeilen nur die t_sipm_{}

t_sipm_0  t_sipm_1  t_sipm_10  t_sipm_11  t_sipm_12  t_sipm_13  \
0       0.0633    0.0042     0.0000     0.0000     0.0000     0.0000   
1       0.0639    0.0000     0.0000     0.0000     0.0000     0.0000   
2       0.0634    0.0000     0.0001     0.0000     0.0000     0.0000   
3       0.0608    0.0050     0.0001     0.0000     0.0000     0.0000   
4       0.0550    0.0144     0.0000     0.0000     0.0000     0.0000   
5       0.0577    0.0012     0.0000     0.0000     0.0000     0.0000   
6       0.0605    0.0000     0.0001     0.0000     0.0001     0.0000   
7       0.0524    0.0000     0.0000     0.0000     0.0000     0.0000   
8       0.0564    0.0001     0.0000     0.0000     0.0001     0.0000   
9       0.0547    0.0000     0.0000     0.0000     0.0000     0.0001   
10      0.0621    0.0022     0.0000     0.0000     0.0000     0.0000   
11      0.0558    0.0118     0.0000     0.0000     0.0000     0.0000   
12      0.0455    0.0203     0.0000     0.0000     0.0000     0.0000   
13      0.0461    0.0126     0.0000     0.0000     0.0000     0.0000   
14      0.0478    0.0001     0.0000     0.0000     0.0000     0.0001   
15      0.0513    0.0000     0.0000     0.0000     0.0000     0.0000   
16      0.0492    0.0000     0.0000     0.0000     0.0000     0.0000   
17      0.0447    0.0000     0.0000     0.0000     0.0000     0.0001   
18      0.0467    0.0000     0.0000     0.0000     0.0000     0.0000   
19      0.0467    0.0001     0.0000     0.0000     0.0000     0.0000   
20      0.0496    0.0000     0.0000     0.0000     0.0000     0.0001   
21      0.0436    0.0000     0.0000     0.0000     0.0002     0.0000   
22      0.0461    0.0138     0.0000     0.0000     0.0000     0.0000   
23      0.0471    0.0227     0.0000     0.0000     0.0000     0.0000   
24      0.0376    0.0301     0.0000     0.0001     0.0000     0.0000   
25      0.0405    0.0217     0.0000     0.0000     0.0000     0.0000   
26      0.0412    0.0106     0.0000     0.0000     0.0001     0.0000   
27      0.0421    0.0000     0.0000     0.0000     0.0000     0.0000   
28      0.0399    0.0000     0.0000     0.0000     0.0000     0.0000   
29      0.0421    0.0000     0.0000     0.0000     0.0000     0.0000   
...        ...       ...        ...        ...        ...        ...   
5910    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5911    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5912    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5913    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5914    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5915    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5916    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5917    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5918    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5919    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5920    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5921    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5922    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5923    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5924    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5925    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5926    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5927    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5928    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5929    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5930    0.0001    0.0000     0.0000     0.0000     0.0000     0.0000   
5931    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5932    0.0000    0.0000     0.0000     0.0000     0.0000     0.0000   
5933    0.0000    0.0000     0.0000     0.0000

In [216]:
rest_probability = 1-response_cols.sum(axis=1)   #1- aufaddierte Wahrscheinlichkeit in einer Zeile
#rest_probability                                   #Restwahrscheinlichkeit für jede Zeile

In [217]:
result= pd.concat([response_cols,rest_probability],axis=1)
#result.rename(columns = {0 : 't_sipm_non'})
result=result.rename(columns = {0:'t_sipm_non'})
#result.rename(columns={'0':'t_sipm_non'}, inplace=True)
#del result['t_sipm_non']
#result                                             #vollstaendige Tabelle mit allen t_sipm, inkl. t_sipm_non

In [218]:
#result.sum(axis=1) #Kontrolle, ob die Summe pro Zeile = 1

In [289]:
response_array = response_cols.values

In [290]:
indices

array([ 20,  36, 344,  54,  76,   3, 539,  20,   9,   2,  77,  20,  77,
         2, 350,  54,   3,  10,  20,  20,   9,  35,   2,  20,   9,  10,
        10, 135,  21,  20,  21, 898,   9,  77,  20,   9,  11, 299])

In [232]:
#for i in range(len(indices)):            Gehe alle indices der photonen durch 
#    print(indices[i])                    -> gebe den index aus
#    print(result.iloc[indices[i],:])     -> gibt die zu diesem index gehörenden zeile von result aus
                                          #d.h. alle t_sipm_{} sowie Wert 

In [273]:
a = list()
b = list()

In [284]:
for i in range(len(indices)):            #fuer alle Photonen mit Index i wird nun aus der zugehoerigen Reihe aus result
    print(indices[i])                    #gewichtet mit der Wahrscheinlichkeit der Eintraege ein sipm (dessen response
    #result.iloc[indices[i],:]           #wert)gezogen
    resp = (np.random.choice(result.iloc[indices[i]],p=result.iloc[indices[i],:])) 
    a.append(indices[i])                 #fuege indices der photonen in eine liste
    b.append(resp)                       #fuege random response in zweite liste
    print(resp)

20
0.9157
36
0.9159
344
0.9213
54
0.9163
76
0.9153
3
0.9254
539
0.9239
20
0.9157
9
0.9156
2
0.9227
77
0.917
20
0.9157
77
0.917
2
0.9227
350
0.0181
54
0.9163
3
0.9254
10
0.909
20
0.9157
20
0.0496
9
0.9156
35
0.9095
2
0.0634
20
0.9157
9
0.9156
10
0.909
10
0.909
135
0.9192
21
0.9195
20
0.9157
21
0.9195
898
0.923
9
0.9156
77
0.917
20
0.9157
9
0.9156
11
0.9192
299
0.9153


In [285]:
print(a)
print(b)

[20, 20, 36, 344, 54, 76, 3, 539, 20, 9, 2, 77, 20, 77, 2, 350, 54, 3, 10, 20, 20, 9, 35, 2, 20, 9, 10, 10, 135, 21, 20, 21, 898, 9, 77, 20, 9, 11, 299, 20, 20, 20, 20, 36, 344, 54, 76, 3, 539, 20, 9, 2, 77, 20, 77, 2, 350, 54, 3, 10, 20, 20, 9, 35, 2, 20, 9, 10, 10, 135, 21, 20, 21, 898, 9, 77, 20, 9, 11, 299, 20, 36, 344, 54, 76, 3, 539, 20, 9, 2, 77, 20, 77, 2, 350, 54, 3, 10, 20, 20, 9, 35, 2, 20, 9, 10, 10, 135, 21, 20, 21, 898, 9, 77, 20, 9, 11, 299]
[0.91569999999999996, 0.91569999999999996, 0.91589999999999994, 0.92130000000000001, 0.9163, 0.9153, 0.9254, 0.92389999999999994, 0.91569999999999996, 0.91559999999999997, 0.92269999999999996, 0.91700000000000004, 0.91569999999999996, 0.91700000000000004, 0.92269999999999996, 0.92130000000000001, 0.9163, 0.9254, 0.90900000000000003, 0.91569999999999996, 0.91569999999999996, 0.91559999999999997, 0.90949999999999998, 0.063399999999999998, 0.91569999999999996, 0.91559999999999997, 0.90900000000000003, 0.90900000000000003, 0.919200000000

In [272]:
df = pd.DataFrame(list(zip(a,b)))
df.rename(columns={0:'photon_index'}, inplace=True)
df.rename(columns={1:'pde'}, inplace=True)
df

photon_index     pde
0             20  0.9157
1             36  0.9159
2            344  0.9213
3             54  0.0234
4             76  0.9153
5              3  0.9254
6            539  0.9239
7             20  0.0496
8              9  0.9156
9              2  0.9227
10            77  0.0352
11            20  0.9157
12            77  0.9170
13             2  0.9227
14           350  0.0451
15            54  0.9163
16             3  0.9254
17            10  0.9090
18            20  0.0496
19            20  0.9157
20             9  0.9156
21            35  0.9095
22             2  0.9227
23            20  0.9157
24             9  0.0547
25            10  0.9090
26            10  0.9090
27           135  0.9192
28            21  0.9195
29            20  0.0496
30            21  0.9195
31           898  0.9230
32             9  0.9156
33            77  0.9170
34            20  0.9157
35             9  0.9156
36            11  0.0558
37           299  0.9153

In [262]:
df['detected'] = np.random.uniform(0, 1, len(df)) <= df[1]

In [265]:
print(df['detected'])

0      True
1      True
2     False
3     False
4      True
5      True
6      True
7     False
8      True
9      True
10    False
11     True
12     True
13     True
14    False
15     True
16     True
17     True
18    False
19     True
20     True
21     True
22     True
23     True
24    False
25    False
26    False
27     True
28     True
29    False
30     True
31     True
32     True
33     True
34     True
35     True
36    False
37     True
Name: detected, dtype: bool


In [266]:
df_detected = df[df.detected]
df_detected

0       1 detected
0    20  0.9157     True
1    36  0.9159     True
4    76  0.9153     True
5     3  0.9254     True
6   539  0.9239     True
8     9  0.9156     True
9     2  0.9227     True
11   20  0.9157     True
12   77  0.9170     True
13    2  0.9227     True
15   54  0.9163     True
16    3  0.9254     True
17   10  0.9090     True
19   20  0.9157     True
20    9  0.9156     True
21   35  0.9095     True
22    2  0.9227     True
23   20  0.9157     True
27  135  0.9192     True
28   21  0.9195     True
30   21  0.9195     True
31  898  0.9230     True
32    9  0.9156     True
33   77  0.9170     True
34   20  0.9157     True
35    9  0.9156     True
37  299  0.9153     True

In [277]:
df_detected.columns = 'pixel', 'pde', 'detected'

In [278]:
df_detected.groupby('pixel')['pde'].count()

pixel
2      3
3      2
9      4
10     1
20     5
21     2
35     1
36     1
54     1
76     1
77     2
135    1
299    1
539    1
898    1
Name: pde, dtype: int64